"use client";
import { trackAudioLabel } from '../../data/music/catalog';
import { Play,Pause,SkipBack,SkipForward,Heart,ChevronUp } from 'lucide-react';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '../ui/sheet';
import { PaintedExpression } from '../melo/PaintedExpression';
import { findTrack } from '../../data/music/catalog';
import { whyTrack } from '../../lib/music/recommendation';
import type { LiveMelo } from '../melo/live/useLiveMelo';
export const clock=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export function Player({melo}:{melo:LiveMelo}) {
  const a=melo.audio,position=a.queue.indexOf(a.song.id),next=findTrack(a.queue[(position+1)%a.queue.length]);
  const controls=(prefix:string)=><div className="global-controls"><button aria-label={`${prefix}上一首`} onClick={()=>melo.skip(-1)}><SkipBack size={18}/></button><button aria-label={`${prefix}${a.playing?'暂停':'播放'}`} disabled={a.loading} onClick={a.toggle}>{a.playing?<Pause size={21}/>:<Play size={21}/>}</button><button aria-label={`${prefix}下一首`} onClick={()=>melo.skip(1)}><SkipForward size={18}/></button></div>;
  const progress=(label:string)=><div className="global-progress"><time>{clock(a.progress)}</time><input type="range" aria-label={label} value={a.progress} min={0} max={a.duration-.1} step={.1} onChange={e=>a.seek(+e.target.value)}/><time>{clock(a.duration)}</time></div>;
  return <>{a.hasStarted&&!melo.nowPlaying&&<aside className="global-player" aria-label="全局音乐播放器"><button className="global-song" onClick={()=>melo.setNowPlaying(true)} aria-label="展开正在播放"><img src={a.song.cover} alt="" width="48" height="48"/><span><strong>{a.song.title}</strong><small>{a.song.artist} · {a.loading?'加载声音…':a.playing?'陪你听着':'暂停片刻'}</small></span></button>{controls('全局播放器')}{progress('全局播放进度')}<button aria-label="全局收藏音乐" aria-pressed={melo.liked} disabled={!!melo.busy} onClick={()=>void melo.favorite()}><Heart size={19} fill={melo.liked?'currentColor':'none'}/></button><button aria-label="展开 Now Playing" onClick={()=>melo.setNowPlaying(true)}><ChevronUp size={20}/></button></aside>}
  <Sheet open={melo.nowPlaying} onOpenChange={melo.setNowPlaying}><SheetContent side="bottom" className="now-playing" data-lenis-prevent><SheetTitle>NOW PLAYING</SheetTitle><SheetDescription>这一首，不用认真听完也没关系。</SheetDescription><div className="now-layout"><img className="now-cover" src={a.song.cover} alt={`${a.song.title} 氛围封面`}/><div><span className="world-label">{trackAudioLabel(a.song)}</span><h2>{a.song.title}</h2><p>{a.song.artist}</p><div className="now-companion" data-mode={melo.mode} style={{opacity:.65+Math.min(.35,Math.max(...a.levels)/240)}}><PaintedExpression expression={melo.expression} thumbnail reduced={melo.reduced}/><p>这一首，不用认真听完也没关系。</p></div><div className="real-wave" aria-hidden="true">{a.levels.map((v,i)=><i key={i} style={{height:(melo.reduced?8:v)+'px'}}/>)}</div>{progress('正在播放进度')}{controls('正在播放')}<label className="now-volume">音量<input type="range" aria-label="正在播放音量" min={0} max={1} step={.01} value={a.volume} onChange={e=>a.setVolume(+e.target.value)}/></label><div className="now-why"><h3>Why this song</h3>{whyTrack(a.song,melo.signal).map(line=><p key={line}>{line}</p>)}<p>下一首 · {next?.title||a.song.title}</p></div></div></div><p className="now-line">把没说完的话，留给耳机里的夜晚。</p></SheetContent></Sheet></>;
}
